<?php

//include head scripts
require_once 'views/header.phtml';

?>
<canvas id="myCanvas" width="10000" height="8000"></canvas>
<script>
  $( document ).ready(function() {
      draw_truss('<?php echo json_encode($this->results->nodes); ?>', '<?php echo json_encode($this->results->elements); ?>', '<?php echo json_encode($this->results->legend); ?>', .1);
  });
</script>
<?php

//include footer
require_once 'views/footer.phtml';

?>
